import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent

STEAM_PATH = Path("C:/Steam")
AOE2DE_PATH = STEAM_PATH / "steamapps" / "common" / "AoE2DE"

AOE2DE_DAT_PATH = AOE2DE_PATH / "resources" / "_common" / "dat"
AOE2DE_WIDGETUI_PATH = AOE2DE_PATH / "widgetui"

PROJECT_DAT_PATH = PROJECT_ROOT / "resources" / "_common" / "dat"
PROJECT_WIDGETUI_PATH = PROJECT_ROOT / "widgetui"

OFFICIAL_DATA_FILE = AOE2DE_DAT_PATH / "empires2_x2_p1.dat"
OFFICIAL_CIVILIZATIONS_FILE = AOE2DE_DAT_PATH / "civilizations.json"
OFFICIAL_CIVTECHTREES_FOLDER = AOE2DE_DAT_PATH / "CivTechTrees"
OFFICIAL_LINKED_TECHS_FILE = AOE2DE_DAT_PATH / "linkedTechs.json"
OFFICIAL_DROPSITES_FILE = AOE2DE_DAT_PATH / "dropsites.json"
OFFICIAL_FUTUR_AVAILABLE_UNITS_FILE = AOE2DE_DAT_PATH / "futuravailableunits.json"
OFFICIAL_ICONS_FILE = AOE2DE_WIDGETUI_PATH / "icons.json"
OFFICIAL_MATERIALS_FILE = AOE2DE_WIDGETUI_PATH / "materials.json"

OUTPUT_DATA_FILE = PROJECT_DAT_PATH / "empires2_x2_p1.dat"
OUTPUT_CIVILIZATIONS_FILE = PROJECT_DAT_PATH / "civilizations.json"
OUTPUT_CIVTECHTREES_FOLDER = PROJECT_DAT_PATH / "CivTechTrees"
OUTPUT_LINKED_TECHS_FILE = PROJECT_DAT_PATH / "linkedTechs.json"
OUTPUT_DROPSITES_FILE = PROJECT_DAT_PATH / "dropsites.json"
OUTPUT_FUTUR_AVAILABLE_UNITS_FILE = PROJECT_DAT_PATH / "futuravailableunits.json"
OUTPUT_ICONS_FILE = PROJECT_WIDGETUI_PATH / "icons.json"
OUTPUT_MATERIALS_FILE = PROJECT_WIDGETUI_PATH / "materials.json"

CHANGES_FILE = PROJECT_DAT_PATH / "changes.json"
CIV_CHANGES_FILE = PROJECT_DAT_PATH / "civ_changes.json"
CTT_CHANGES_FILE = PROJECT_DAT_PATH / "ctt_changes.json"
LT_CHANGES_FILE = PROJECT_DAT_PATH / "lt_changes.json"
DR_CHANGES_FILE = PROJECT_DAT_PATH / "dr_changes.json"
FAU_CHANGES_FILE = PROJECT_DAT_PATH / "fau_changes.json"
IM_CHANGES_FILE = PROJECT_WIDGETUI_PATH / "im_changes.json"