//  全局量定义

//  资源定义
extern const int cAttributeVarangianLootProductivity = 384; //  瓦兰吉卫队黄金产率
extern const int cAttributeWubaoFoodWoodProductivity = 385; //  坞堡食物和木材产出速率
extern const int cAttributeFishTrapProductivity = 387;
extern const int cAttributeCavalryLootBuildingGoldProductivity = 389;   //  骑兵掠夺建筑黄金产率
extern const int cAttributeInfantryLootFarmFoodProductivity = 390;  //  步兵掠夺农田产出食物速率
extern const int cAttributeHunterFoodProductivity = 391;    //  猎人食物自动产率
extern const int cAttributeFarmFoodGenerateProductivity = 392;  //  农田食物产出速率
extern const int cAttributeWubaoGoldProductivity = 393; //  坞堡黄金产出速率
extern const int cAttributeRelicPurchaseLimit = 394;    //  圣物可购买数
extern const int cAttributeLoanLimit = 396; //  借贷可用数量
extern const int cAttributeGoldFishingProductivity = 397;   //  捕鱼黄金产出速率
extern const int cAttributeTaboriteWarriorProductivity = 398;   //  塔博尔战士资源产出速率
extern const int cAttributeHospitallerKnightCharge = 409;   //  医院骑士充能
extern const int cAttributeHospitallerKnightChargeRate = 410;   //  医院骑士充能效率
extern const int cAttributeShrineSpawnUnitID = 411; //  圣坛生产的单位ID
extern const int cAttributeMagyarRelicAttackBonus = 412;    //  马扎尔圣物加成的攻击力
extern const int cAttributeVikingRaiderKills = 413; //  维京掠夺者击杀数
extern const int cAttributeApostleProductivity = 414;   //  使徒黄金产出速率
extern const int cAttributePolesFoodObtained = 415; //  维利奇卡盐矿已经奖励的食物数
extern const int cAttributeSpanishExplorerGoldCalced = 416; //  西班牙探险家已经计算的黄金数
extern const int cAttributeWarShipFoodProductivity = 417; //  马来战船产生食物的速率
extern const int cAttributeRecruitMercenaryCost = 418;  //  招募佣兵所需积累的资源, 每过一段时间获得1次招募机会
extern const int cAttributeCurrentTime = 419;   //  当前时间 +1
extern const int cAttributeTechEffectTime = 420;    //  科技效果剩余的持续时间
extern const int cAttributeFrankLoan = 421; //  法兰克放贷数额
extern const int cAttributeIxipltaKillCount = 422;   //  阿兹特克独特科技的击杀数统计
extern const int cAttributeHospitallerKnightAbilityTime = 423;  //  医院骑士技能剩余持续时间
extern const int cAttributeShrineSpawnCount = 424;  //  圣坛已生产单位的次数
extern const int cAttributeCondottieroMercenaryNum = 434;   //  意大利佣兵生成数量
extern const int cAttributeTeam = 435;   //  队伍编号
extern const int cAttributeRelicCount = 436;    //  圣物计数
extern const int cAttributeGothsVillagerBonus = 437;    //  哥特文明加成已经奖励的村民数
extern const int cAttributeSoheiProgress = 438; //  日本僧兵产生进度
extern const int cAttributeDacaoguCalcedValue = 439;    //  契丹打草谷已经计算的摧毁价值数
extern const int cAttributeChineseTCCount = 440;    //  中国城镇中心数量


//  单位ID定义
extern const int TotalObjects = 4061;
extern const int AssassinID = 4001;
extern const int StreltsyID = 4002;
extern const int KhevsuretiWarriorID = 4003;
extern const int EliteKhevsuretiWarriorID = 4004;
extern const int HandcannonAshigaruID = 4005;
extern const int YumiAshigaruID = 4006;
extern const int VeteranYumiAshigaruID = 4007;
extern const int EliteYumiAshigaruID = 4008;
extern const int WoodenFortressID = 4009;
extern const int ManilaGalleoID = 4010;
extern const int VarangianID = 4011;
extern const int EliteVarangianID = 4013;
extern const int SipahiID = 4014;
extern const int EliteSipahiID = 4015;
extern const int WubaoID = 4016;
extern const int EarlyCavalryArcherID = 4017;
extern const int ParthianCavalryArcherID = 4020;
extern const int EliteParthianCavalryArcherID = 4021;
extern const int InvisiblePCAID = 4022;
extern const int InvisibleEPCAID = 4023;
extern const int ChanyuID = 4024;
extern const int ChariotArcherID = 4025;
extern const int RungScoutID = 4027;
extern const int InvisibleRungScoutID = 4028;
extern const int EliteRungScoutID = 4029;
extern const int InvisibleEliteRungScoutID = 4030;
extern const int SwissLancerID = 4031;
extern const int LembosID = 4032;
extern const int ConscriptedArmyID = 4033;
extern const int CamelLancerID = 4034;
extern const int EliteCamelLancerID = 4035;
extern const int HobelarID = 4036;
extern const int EliteHobelarID = 4037;
extern const int HospitallerKnightID = 4038;
extern const int EliteHospitallerKnightID = 4039;
extern const int CrusaderKnightID = 4041;
extern const int SoheiID = 4042;
extern const int VikingRaiderID = 4044;
extern const int SofaID = 4045;
extern const int EliteSofaID = 4046;
extern const int FlameThrowerID = 4047;
extern const int TaboriteWarriorID = 4048;
extern const int ShrineID = 4049;
extern const int KhanID = 4050;
extern const int ExtraConscriptedArmyID = 4051;
extern const int InvisibleDeerSpawnerID = 4052;
extern const int SpawnedDeerID = 4054;
extern const int ToungooWarriorID = 4055;
extern const int EliteToungooWarriorID = 4057;
extern const int MansabdarID = 4058;
extern const int VeteranMansabdarID = 4059;
extern const int EliteMansabdarID = 4060;


extern const int ArcherID = 4;
extern const int HandCannoneerID = 5;
extern const int EliteSkirmisherID = 6;
extern const int SkirmisherID = 7;
extern const int MangudaiID = 11;
extern const int CrossbowmanID = 24;
extern const int BatteringRamID = 35;
extern const int BombardCannonID = 36;
extern const int KnightID = 38;
extern const int CavalryArcherID = 39;
extern const int CastleID = 82;
extern const int MilitiaID = 74;
extern const int ManAtArmsID = 75;
extern const int LongSwordmanID = 77;
extern const int SpearmanID = 93;
extern const int ImperialCamelRiderID = 207;
extern const int CavalierID = 283;
extern const int CamelRiderID = 329;
extern const int HeavyCamelRiderID = 330;
extern const int PikemanID = 358;
extern const int HalberdierID = 359;
extern const int CappedRamID = 422;
extern const int HussarID = 441;
extern const int ScoutCavalryID = 448;
extern const int TwoHandedSwordmanID = 473;
extern const int HeavyCavalryArcherID = 474;
extern const int ArbalesterID = 492;
extern const int FireGalleyID = 529;
extern const int EliteLongbowmanID = 530;
extern const int EliteThrowingAxemanID = 531;
extern const int EliteWoadRaiderID = 534;
extern const int HeavyScorpionID = 542;
extern const int TransportShipID = 545;
extern const int LightCavalryID = 546;
extern const int SiegeRamID = 548;
extern const int OnagerID = 550;
extern const int EliteMangudaiID = 561;
extern const int ChampionID = 567;
extern const int PaladinID = 569;
extern const int SiegeOnagerID = 588;
extern const int EagleScoutID = 751;
extern const int EliteEagleWarriorID = 752;
extern const int EagleWarriorID = 753;
extern const int TarkanID = 755;
extern const int EliteTarkanID = 757;
extern const int WarWagonID = 827;
extern const int EliteWarWagonID = 829;
extern const int CondottieroID = 882;
extern const int HeavyPikemanID = 892;
extern const int CamelArcherID = 1007;
extern const int EliteCamelArcherID = 1009;
extern const int GenitourID = 1010;
extern const int EliteGenitourID = 1012;
extern const int RattanArcherID = 1129;
extern const int EliteRattanArcherID = 1131;
extern const int BattleElephantID = 1132;
extern const int EliteBattleElephantID = 1134;
extern const int ImperialSkirmisherID = 1155;
extern const int KeshikID = 1228;
extern const int EliteKeshikID = 1230;
extern const int FeudalBatteringRamID = 1258;
extern const int FlameCamelID = 1263;
extern const int SteppeLancerID = 1370;
extern const int EliteSteppeLancerID = 1372;
extern const int WingedHussarID = 1707;
extern const int CamelScoutID = 1755;
extern const int LegionaryID = 1793;
extern const int MonaspaID = 1803;
extern const int EliteMonaspaID = 1805;
extern const int MuleCartID = 1808;
extern const int WarriorPriestID = 1811;
extern const int SavarID = 1813;
extern const int FireLancerID = 1901;
extern const int EliteFireLancerID = 1903;
extern const int IronPagodaID = 1908;
extern const int EliteIronPagodaID = 1910;
extern const int LiaoDaoID = 1920;
extern const int EliteLiaoDaoID = 1922;
extern const int MountedTrebuchetID = 1923;
extern const int WhiteFeatherGuardID = 1959;
extern const int EliteWhiteFeatherGuardID = 1961;


//  攻击类型定义
extern const int TotalAttackForms = 106;
extern const int cDamageClassMonastery = 101;
extern const int cDamageClassSiegeWeaponAttack = 104;
extern const int cDamageClassLightCavalry = 105;


extern const int HospitallerKnightMaxCharge = 300; //   医院骑士技能充能
extern const float ShrineMaxCharge = 1200.0;    //  圣坛最大充能
extern const int SatrapAuraRange = 10;  //  波斯总督光环范围
extern const int MalayTCAuraRange = 10;